/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package barberos;

import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author carlo
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barbero1 = new javax.swing.JButton();
        barbero2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        fila = new javax.swing.JLabel();
        silla1 = new javax.swing.JButton();
        silla2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        barbero1.setText("B1");

        barbero2.setText("B2");

        jLabel1.setText("CLIENTES EN FILA:");

        fila.setText("jLabel2");

        silla1.setText("jButton1");

        silla2.setText("jButton1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fila))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(barbero1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(barbero2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(74, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(silla1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(silla2)
                .addGap(127, 127, 127))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(barbero1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(barbero2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(silla1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(silla2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fila))
                .addGap(77, 77, 77))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   public void EstadoBarbero(int estado, int numbarbero){
       if(numbarbero==1){
        switch (estado) {
            case 1 -> {
                barbero1.setText("DESCANSANDO");
                barbero1.setBackground(Color.BLUE);
            }
            case 2 ->{
                barbero1.setText("CORTANDO PELO");
                barbero1.setBackground(Color.GREEN);
            }
            case 3 ->{
                barbero1.setText("TERMINO DE CORTAR PELO");
                barbero1.setBackground(Color.RED);
            }
            default -> {
            }
        }   
       }else{
        switch (estado) {
            case 1 -> {
                barbero2.setText("DESCANSANDO");
                barbero2.setBackground(Color.BLUE);
            }
            case 2 ->{
                barbero2.setText("CORTANDO PELO");
                barbero2.setBackground(Color.GREEN);
            }
            case 3 ->{
                barbero2.setText("TERMINO DE CORTAR PELO");
                barbero2.setBackground(Color.RED);
            }
            default -> {
            }
        }
       }
        
   }
   
   public void EstadoSilla(int estado, int numsilla,int cliente){
       if(numsilla==1){
        switch (estado) {
            case 1 -> {
                silla1.setVisible(true);
                silla1.setText("CLIENTE: "+cliente);
                silla1.setBackground(Color.ORANGE);
            }
            case 2 ->{
                silla1.setVisible(false);
            }
            
            default -> {
            }
        }   
       }else{
        switch (estado) {
            case 1 -> {
                silla2.setVisible(true);
                silla2.setText("CLIENTE: "+cliente);
                silla2.setBackground(Color.ORANGE);
            }
            case 2 ->{
                silla2.setVisible(false);
            }
            default -> {
            }
        }
       }
        
   }
   
   public void NumFila(int fila){
        this.fila.setText(fila+"");
   }
    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton barbero1;
    private javax.swing.JButton barbero2;
    private javax.swing.JLabel fila;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton silla1;
    private javax.swing.JButton silla2;
    // End of variables declaration//GEN-END:variables
}
